packages:
  device_base: "github://RobinLinde/esphome-config/device_base_api.yaml@main"
  default_sensors: "github://RobinLinde/esphome-config/common/sensor/default.yaml@main"
  default_text_sensors: "github://RobinLinde/esphome-config/common/text_sensor/default.yaml@main"
  default_button: "github://RobinLinde/esphome-config/common/button/default.yaml@main"

external_components:
  - source:
      type: git
      url: https://github.com/wjtje/esphome
      ref: lsc-power-monitoring-fix
    components: [pulse_counter]

bk72xx:
  board: cb2s

logger:
  hardware_uart: UART2

switch:
  - platform: gpio
    pin: 8
    name: "${friendly_name} Relay"
    device_class: outlet
    id: relay
    restore_mode: ALWAYS_OFF
    on_turn_on:
      - if:
          condition:
            switch.is_on: output_led_control
          then:
            - switch.turn_on: output_led
    on_turn_off:
      - switch.turn_off: output_led

  - platform: gpio
    pin: 6
    id: output_led

  - platform: template
    name: "${friendly_name} Button Control"
    id: button_control
    optimistic: true
    entity_category: config
    icon: mdi:gesture-tap
    restore_mode: RESTORE_DEFAULT_ON

  - platform: template
    name: "${friendly_name} Output LED"
    id: output_led_control
    optimistic: true
    entity_category: config
    restore_mode: RESTORE_DEFAULT_ON
    turn_on_action:
      - if:
          condition:
            switch.is_on: relay
          then:
            - switch.turn_on: output_led
    turn_off_action:
      - switch.turn_off: output_led

status_led:
  pin: 10

binary_sensor:
  - platform: gpio
    pin:
      number: 7
      inverted: true
      mode:
        input: true
        pullup: true
    name: "${friendly_name} Button"
    filters:
      - delayed_on_off: 10ms
    on_press:
      if:
        condition:
          switch.is_on: button_control
        then:
          - switch.toggle: relay

sensor:
  - platform: hlw8012
    model: BL0937
    current_resistor: 0.0011
    voltage_divider: 1661.8
    change_mode_every: 2
    sel_pin:
      number: 11
      inverted: true
    cf_pin: 26
    cf1_pin: 24
    current:
      name: "${friendly_name} Current"
    voltage:
      name: "${friendly_name} Voltage"
    power:
      name: "${friendly_name} Power"
    energy:
      name: "${friendly_name} Energy"
    update_interval: 5s
