esphome:
  name: $devicename

logger:

ota:
  password: $ota_password

wifi:
  ssid: $wifi_ssid
  password: $wifi_password
  fast_connect: true

  ap:
      ssid: "$friendly_name Fallback"
      password: $fallback_password

captive_portal:

api:
  encryption: 
    key: $api_key