packages:
  device_base: "github://RobinLinde/esphome-config/device_base_api.yaml@main"
  default_sensors: "github://RobinLinde/esphome-config/common/sensor/default.yaml@main"
  default_text_sensors: "github://RobinLinde/esphome-config/common/text_sensor/default.yaml@main"
  default_button: "github://RobinLinde/esphome-config/common/button/default.yaml@main"

esp8266:
  board: esp8285

binary_sensor:
  - platform: gpio
    pin: 
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    name: "${friendly_name} Button"
    on_press:
      then:
        - switch.toggle: relay

output:
  - platform: gpio
    pin: GPIO12
    id: relay_output

switch:
  - platform: output
    name: "${friendly_name} Relay"
    output: relay_output
    id: relay

status_led:
  pin: 
    number: GPIO13
    inverted: True

light:
  - platform: binary
    name: "${friendly_name} Light"
    output: relay_output
    restore_mode: RESTORE_AND_OFF
    disabled_by_default: True
    